apiVersion: apps/v1
kind: Deployment
metadata:
  name: spug
  namespace: default
  labels:
    app: spug
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: spug
  template:
    metadata:
      labels:
        app: spug
    spec:
      containers:
      - name: spug
        image: spug:local
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 3"]
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: data
          mountPath: /data
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: data
          hostPath:
            path: /home/jin/cmdbv3

---

apiVersion: v1
kind: Service
metadata:
  name: spug-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: "TCP"
      targetPort: 80
      nodePort: 30000
  selector:
    app: spug

